# Generated by Django 3.2 on 2023-12-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20231224_2148'),
        ('reviews', '0008_alter_title_name'),
    ]

    operations = [
    ]
