# Generated by Django 3.2 on 2023-12-28 17:41

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_title_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique_relationships'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, author=django.db.models.expressions.F('title')), name='prevent_self_follow'),
        ),
    ]
