# Generated by Django 3.2 on 2023-12-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20231228_1741'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='prevent_self_follow',
        ),
    ]
