# Generated by Django 3.2 on 2024-01-05 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20231224_2148'),
        ('reviews', '0009_alter_review_unique_together'),
    ]

    operations = [
    ]
