# Generated by Django 3.2 on 2023-12-28 18:06

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_remove_review_prevent_self_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_relationships',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique_relationships'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, title=django.db.models.expressions.F('author')), name='prevent_self_follow'),
        ),
    ]
