# Generated by Django 3.2 on 2023-12-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20231228_1806'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_relationships',
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='prevent_self_follow',
        ),
    ]
