# Generated by Django 3.2 on 2024-01-09 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_alter_review_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10, 'Оценка не может быть больше %(limit_value)s.'), django.core.validators.MinValueValidator(0, 'Оценка не может быть ниже %(limit_value)s.')], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
