# Generated by Django 3.2 on 2024-01-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_alter_review_author'),
        ('reviews', '0012_auto_20240109_1657'),
    ]

    operations = [
    ]
