# Generated by Django 3.2 on 2024-01-25 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_alter_review_author'),
        ('reviews', '0013_merge_20240116_0032'),
    ]

    operations = [
    ]
