# Generated by Django 3.2 on 2023-12-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_auto_20231228_1901'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_relationships',
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='prevent_self_follow',
        ),
    ]
