# Generated by Django 3.2 on 2024-01-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_auto_20240127_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(default=0, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
